title: "Town of Hubbardston Budget Portal"
description: "A modern, interactive platform for financial transparency and community engagement."
theme: null  
markdown: kramdown
exclude: ["README.md"]

# Ensure Jekyll includes layouts and assets
include:
  - _layouts
  - docs/assets
  - _data

# Set the base URL for GitHub Pages
baseurl: "/FY26"  
permalink: pretty

# Enable Jekyll plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation links
nav_links:
  Home: "index.html"
  Revenue: "revenue.html"
  Expenditures: "expenditures.html"
  Dashboard: "dashboard/index.html"

# Default metadata for pages
defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

# Enable site-wide settings
theme_settings:
  primary_color: "#004400"  
  secondary_color: "#F5F5F5"
  background_image: "docs/assets/hubbardston_bg.jpg"
  logo: "docs/assets/seal.png"
