# Site Information
title: "Town of Hubbardston Budget Portal"
description: "A modern, interactive platform for financial transparency and community engagement."

# GitHub Pages Base URL (Adjust if deploying elsewhere)
baseurl: "/FY26" 
url: "https://NBoudreauMA.github.io"

# Build Configuration
theme: null
markdown: kramdown
exclude: ["README.md"]

# Ensure Jekyll processes necessary folders
include:
  - _data
  - _layouts
  - docs/assets
  - docs/budget.csv  # Ensure the CSV file is processed by Jekyll

# Plugins for SEO and Sitemap
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation Links
nav_links:
  Home: "/docs/index.html"
  Revenue: "/docs/revenue.html"
  Expenditures: "/docs/expenditures.html"
  Dashboard: "/dashboard/index.html"

# Permalink Settings for Pretty URLs
permalink: pretty
