title: "Town of Hubbardston Budget Repository"
description: "Transparent, Interactive Budget Book "
theme: null  # Disables GitHub's default theme
markdown: kramdown
exclude: ["README.md"]

# Include the _layouts folder from the root
include:
  - _layouts

# Set the base URL in case GitHub Pages needs it
baseurl: "/FY26"

# Permalinks to ensure clean URLs
permalink: pretty
