title: "Town of Hubbardston Budget Portal"
description: "A modern, interactive platform for financial transparency and community engagement."
theme: null  # Disables GitHub's default theme
markdown: kramdown
exclude: ["README.md"]

# Ensure Jekyll includes layouts and assets
include:
  - _layouts
  - docs/assets

# Set a clean base URL for GitHub Pages
baseurl: "/FY26"  # Adjust if deploying elsewhere
permalink: pretty

# Enable plugins (if GitHub Pages allows them)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation links for dynamic use (Optional, but useful)
nav_links:
  Home: "index.html"
  Revenue: "revenue.html"
  Expenditures: "expenditures.html"
  Dashboard: "dashboard/index.html"

# Default metadata for pages
defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

# Theme settings (Used in CSS or site-wide styles)
theme_settings:
  primary_color: "#004400"  # Dark Green (Hubbardston Style)
  secondary_color: "#F5F5F5"  # Light Gray for contrast
  background_image: "docs/assets/hubbardston_bg.jpg"  # Ensure this file exists
  logo: "docs/assets/seal.png"

# Jekyll Build Options
future: true  # Ensure future-dated posts/pages show up
lsi: false  # Disable Latent Semantic Indexing (not needed for static sites)
safe: true  # Keep safe mode enabled for GitHub Pages

# Custom Collections (If Needed)
collections:
  budget:
    output: true
    permalink: /:collection/:path/

# Site Generation Caching (Helps with speed)
keep_files:
  - assets
  - docs/assets

