title: Hubbardston FY26 Budget
description: Comprehensive financial breakdown of Hubbardston's FY26 budget.
theme: jekyll-theme-cayman

github:
  is_project_page: false

nav:
  - title: Dashboard
    url: /dashboard.html
  - title: Revenue
    url: /revenue.html
  - title: Expenditures
    url: /expenditures.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
