theme: jekyll-theme-cayman
title: Hubbardston FY26 Budget
description: Interactive budget proposal site for the Town of Hubbardston, MA.
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
