title: "Hubbardston Budget Portal"
description: "An interactive portal for Hubbardston's FY26 budget"
baseurl: "/FY26"
url: "https://nboudreauma.github.io"

# Build settings
markdown: kramdown
theme: minima

# GitHub Pages settings
github:
  is_project_page: false

# Default Layout
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Include files and folders
include:
  - docs
  - _layouts
  - assets

# Exclude files and folders
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
