title: "Town of Hubbardston Budget Portal"
description: "A modern, interactive platform for financial transparency and community engagement."
theme: null
markdown: kramdown
exclude: ["README.md"]

# Ensure Jekyll processes the _data folder
include:
  - _data
  - _layouts
  - docs/assets

# Enable plugins (if GitHub Pages allows them)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Set up navigation links
nav_links:
  Home: "index.html"
  Revenue: "revenue.html"
  Expenditures: "expenditures.html"
  Dashboard: "dashboard/index.html"
