title: FY26 Budget
description: A detailed overview of the FY26 budget expenditures for the Town of Hubbardston.
theme: jekyll-theme-cayman

# Enable GitHub Pages
github:
  is_project_page: false

# Navigation Links
nav:
  - title: Dashboard
    url: /dashboard.html
  - title: Revenue
    url: /revenue.html
  - title: Budget Expenditures
    url: /expenditures.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
