title: "Hubbardston Budget Portal"
description: "An interactive portal for Hubbardston's FY26 budget, including revenue and expenditures breakdowns."
baseurl: ""  # Removed FY26 to prevent it from appearing at the top
url: "https://yourwebsite.com" # Update with your actual site URL

# Theme settings
theme: minima 
minima:
  skin: auto
  header_pages: []  # Prevents GitHub from adding an extra Home link

# Navigation (Sidebar or Top Navigation)
nav:
  - title: "Home"
    url: "/"
  - title: "Revenue Breakdown"
    url: "/revenue"
  - title: "Expenditures Breakdown"
    url: "/expenditures"
  - title: "Budget Book"
    url: "/budget-book"
  - title: "Contact"
    url: "/contact"

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

# Permalinks
permalink: pretty

# Default Layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Collections
collections:
  budget:
    output: true
    permalink: /:collection/:path/

# Exclude files
exclude:
  - README.md
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - vendor/
