title: "Hubbardston Budget Portal"
description: "An interactive portal for Hubbardston's FY26 budget, including revenue and expenditures breakdowns."
baseurl: "/FY26"  # Ensure this matches the repository name
url: "https://nboudreauMA.github.io"  # Your GitHub Pages URL

# Theme settings
theme: minima
minima:
  skin: auto
  header_pages: []  

# Navigation
nav:
  - title: "Home"
    url: "/FY26/"
  - title: "Revenue"
    url: "/FY26/revenue"
  - title: "Expenditures"
    url: "/FY26/expenditures"
  - title: "Budget Book"
    url: "/FY26/docs/budget-book"
  - title: "Dashboard"
    url: "/FY26/dashboard"

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

# Default Layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Permalinks
permalink: pretty

# Collections (Structured budget data)
collections:
  budget:
    output: true
    permalink: /FY26/:collection/:path/

# Exclude unnecessary files
exclude:
  - README.md
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - vendor/
