title: "Hubbardston Budget Portal"
description: "An interactive portal for Hubbardston's FY26 budget, including revenue and expenditures breakdowns."
baseurl: "/FY26"  # This must match your GitHub repository name
url: "https://nboudreauMA.github.io"  # Your GitHub Pages URL

# Theme settings
theme: minima
minima:
  skin: auto
  header_pages: []  # Prevents extra Home link

# Navigation (Sidebar or Top Navigation)
nav:
  - title: "Home"
    url: "/FY26/"
  - title: "Revenue Breakdown"
    url: "/FY26/revenue"
  - title: "Expenditures Breakdown"
    url: "/FY26/expenditures"
  - title: "Budget Book"
    url: "/FY26/budget-book"
  - title: "Contact"
    url: "/FY26/contact"

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

# Permalinks
permalink: pretty

# Default Layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Collections (For structured budget data)
collections:
  budget:
    output: true
    permalink: /FY26/:collection/:path/

# Exclude files (Prevents unnecessary files from being built)
exclude:
  - README.md
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - vendor/
