title: "Town of Hubbardston Budget Portal"
description: "A modern, interactive platform for financial transparency and community engagement."
theme: null
markdown: kramdown
exclude: ["README.md"]

# Ensure Jekyll includes layouts and assets
include:
  - _layouts
  - docs/assets
  - _data  # ✅ Make sure _data is included

# Set a clean base URL for GitHub Pages
baseurl: "/FY26"  # ✅ Ensure this matches your GitHub Pages repo name
permalink: pretty

# Enable plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation links
nav_links:
  Home: "index.html"
  Revenue: "revenue.html"
  Expenditures: "expenditures.html"
  Dashboard: "dashboard/index.html"

# Default metadata for pages
defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

# Ensure _data files are included
defaults:
  - scope:
      path: "_data"
      type: "data"
    values:
      budget: budget
