title: "Hubbardston FY26 Budget"
description: "A modern municipal budget overview for Hubbardston, MA."
theme: jekyll-theme-cayman

github:
  is_project_page: false

nav:
  - title: Dashboard
    url: /docs/index.html
  - title: Revenue
    url: /docs/revenue.html
  - title: Expenditures
    url: /docs/expenditures.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
