title: "Hubbardston Budget Portal"
description: "An interactive portal for Hubbardston's FY26 budget, including revenue and expenditures breakdowns."
baseurl: "/FY26"
url: "https://nboudreauma.github.io/FY26"

# Theme settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
nav:
  - title: "Revenue Breakdown"
    url: "/revenue"
  - title: "Expenditures Breakdown"
    url: "/expenditures"
  - title: "Capital Planning"
    url: "/capital-planning"
  - title: "Contact"
    url: "/contact"

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

# Permalinks
permalink: pretty

# Collections
collections:
  budget:
    output: true
    permalink: /:collection/:path/

# Exclude files
exclude:
  - README.md
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - vendor/

# Default Layout
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Minima theme settings
minima:
  skin: auto
  header_pages: []  # This removes the default theme header
