title: Hubbardston Budget
baseurl: "" # Keep empty if deploying from root
url: "https://nboudreauMA.github.io" # Your GitHub Pages URL

permalink: pretty

nav:
  - title: Home
    url: /
  - title: Revenue
    url: /docs/revenue.html
  - title: Expenditures
    url: /docs/expenditures.html
